name: Run get_short_range_prediction_to_S3

on:
    workflow_dispatch: # 手動実行を許可
    schedule:
      - cron: '0 21 * * *' # 日本時間 6:00 (UTC 21:00)
      - cron: '0 9 * * *'  # 日本時間 18:00 (UTC 9:00)

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # OIDCトークン発行に必要
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python get_short_range_prediction.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::357665575661:role/get-weather-charts-gha
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: aws s3 cp output/ s3://weather-charts-viewer-gha/ --recursive

      - name: Upload completion flag
        run: |
          touch upload_done.flag
          aws s3 cp upload_done.flag s3://weather-charts-viewer-gha/upload_done.flag

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::357665575661:role/MyStaticSiteStack-GitHubActionsRole4F1BBA26-vAMRPbo4SY9Z
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: aws s3 cp output/ s3://mystaticsitestack-staticwebbucketbbbd7aae-zysfzpac2upn/ --recursive

      - name: Upload completion flag
        run: |
          touch upload_done.flag
          aws s3 cp upload_done.flag s3://mystaticsitestack-staticwebbucketbbbd7aae-zysfzpac2upn/upload_done.flag        
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: short-range-output-zip2
          path: output/
          retention-days: 15
