name: Run test_to_s3

on:
  workflow_dispatch: # 手動実行を許可

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # OIDCトークン発行に必要
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python upload_to_s3.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::357665575661:role/MyStaticSiteStack-GitHubActionsRole4F1BBA26-vAMRPbo4SY9Z
          aws-region: ap-northeast-1

      - name: Upload to S3
        run: aws s3 cp output/ s3://mystaticsitestack-staticwebbucketbbbd7aae-zysfzpac2upn/ --recursive

      - name: Upload completion flag
        run: |
          touch upload_done.flag
          aws s3 cp upload_done.flag s3://mystaticsitestack-staticwebbucketbbbd7aae-zysfzpac2upn/upload_done.flag        
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload_test
          path: output/
          retention-days: 15